name: mydb2

x-podman:
  in_pod: false
  name_separator_compat: false
  default_net_name_compat: false
  default_net_behavior_compat: false

services:
  db2:
    container_name: db2server
    hostname: db2server
    image: icr.io/db2_community/db2:11.5.9.0
    restart: unless-stopped
    privileged: true
    ports:
      # dbport
      - "50000:50000"
      # tsport
      - "55000:55000"
      - "60006:60006"
      - "60007:60007"
    userns_mode: keep-id:uid=1000
    volumes:
      - /home/awhawks/mnt/ixf2Json/myDatabase/db2/database:/database
      - /home/awhawks/mnt/ixf2Json/myDatabase/db2/backup_11.5:/database/backup
      - /home/awhawks/mnt/ixf2Json/myDatabase/db2/export:/adam_export
      - /home/awhawks/mnt/ixf2Json/myDatabase/db2/import:/adam_import
      - /home/awhawks/mnt/ixf2Json/myDatabase/db2/scripts:/adam_scripts
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: db2pass
      DBNAME: ""
      BLU: false
      ENABLE_ORACLE_COMPATIBILITY: false
      UPDATEAVAIL: NO
      TO_CREATE_SAMPLEDB: false
      REPODB: false
      IS_OSXFS: false
      PERSISTENT_HOME: true
      HADR_ENABLED: false
      ETCD_ENDPOINT: ""
      ETCD_USERNAME: ""
      ETCD_PASSWORD: ""
