# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."db2server" = {
    image = "icr.io/db2_community/db2:11.5.9.0";
    environment = {
      "BLU" = "false";
      "DB2INST1_PASSWORD" = "db2pass";
      "DB2INSTANCE" = "db2inst1";
      "DBNAME" = "";
      "ENABLE_ORACLE_COMPATIBILITY" = "false";
      "ETCD_ENDPOINT" = "";
      "ETCD_PASSWORD" = "";
      "ETCD_USERNAME" = "";
      "HADR_ENABLED" = "false";
      "IS_OSXFS" = "false";
      "LICENSE" = "accept";
      "PERSISTENT_HOME" = "true";
      "REPODB" = "false";
      "TO_CREATE_SAMPLEDB" = "false";
      "UPDATEAVAIL" = "NO";
    };
    volumes = [
      "/home/awhawks/mnt/ixf2Json/myDatabase/db2/backup_11.5:/database/backup:rw"
      "/home/awhawks/mnt/ixf2Json/myDatabase/db2/database:/database:rw"
      "/home/awhawks/mnt/ixf2Json/myDatabase/db2/export:/adam_export:rw"
      "/home/awhawks/mnt/ixf2Json/myDatabase/db2/import:/adam_import:rw"
      "/home/awhawks/mnt/ixf2Json/myDatabase/db2/scripts:/adam_scripts:rw"
    ];
    ports = [
      "50000:50000/tcp"
      "55000:55000/tcp"
      "60006:60006/tcp"
      "60007:60007/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=db2server"
      "--network-alias=db2"
      "--network=mydb2_default"
      "--privileged"
    ];
  };
  systemd.services."docker-db2server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-mydb2_default.service"
    ];
    requires = [
      "docker-network-mydb2_default.service"
    ];
    partOf = [
      "docker-compose-mydb2-root.target"
    ];
    upheldBy = [
      "docker-network-mydb2_default.service"
    ];
    wantedBy = [
      "docker-compose-mydb2-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-mydb2_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f mydb2_default";
    };
    script = ''
      docker network inspect mydb2_default || docker network create mydb2_default
    '';
    partOf = [ "docker-compose-mydb2-root.target" ];
    wantedBy = [ "docker-compose-mydb2-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-mydb2-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
