{
  config,
  lib,
  pkgs,
  ...
}: {
  # Define a new option for the admin user
  options.services.headscale = {
    adminUser = lib.mkOption {
      type = lib.types.str;
      default = "awhawks";
      description = "Username for the headscale admin user";
    };
  };

  config = let
    adminUser = config.services.headscale.adminUser;

    aclConfig = {
      # Groups definition
      groups = {
        "group:admins" = ["${adminUser}"];
      };

      acls = [
        # Allow all connections within the tailnet
        {
          action = "accept";
          src = ["*"];
          dst = ["*:*"];
        }
        # Allow admin to connect to their own services
        {
          action = "accept";
          src = ["${adminUser}"];
          dst = ["${adminUser}:*"];
        }
      ];

      # Auto-approvers section for routes
      autoApprovers = {
        routes = {
          "0.0.0.0/0" = ["${adminUser}"];
          "10.0.0.0/8" = ["${adminUser}"];
          "192.168.0.0/16" = ["${adminUser}"];
        };

        exitNode = ["${adminUser}"];
      };
    };
    # Convert to HuJSON format with comments
    aclHuJson = ''
      // Headscale ACL Policy - Generated by NixOS
      // Admin user: ${adminUser}

      ${builtins.toJSON aclConfig}
    '';
    aclFile = pkgs.writeText "acl-policy.hujson" aclHuJson;
  in {
    # Import the headscale module
    # In a real configuration, this would come from the flake input
    # imports = [ inputs.headscale.nixosModules.default ];

    services.headscale = {
      enable = true;

      # Optional: Use a specific package (defaults to pkgs.headscale)
      # package = pkgs.headscale;

      adminUser = "awhawks@gmail.com";
      # Listen on all interfaces (default is 127.0.0.1)
      address = "0.0.0.0";
      port = 3009;
      settings = {
        # The URL clients will connect to
        server_url = "https://hs.hawkstech.org";

        # IP prefixes for the tailnet
        # These use the freeform settings - you can set any headscale config option
        prefixes = {
          v4 = "100.64.0.0/10";
          v6 = "fd7a:115c:a1e0::/48";
          allocation = "sequential";
        };

        # DNS configuration with MagicDNS
        dns = {
          magic_dns = true;
          base_domain = "tailscale.internal.hawkstech.org";

          # Whether to override client's local DNS settings (default: true)
          # When true, nameservers.global must be set
          override_local_dns = true;

          nameservers = {
            global = [ "olivia.ns.cloudflare.com" "1.1.1.1" "8.8.8.8" ];
          };
        };
        # DERP (relay) configuration
        derp = {
          # Use default Tailscale DERP servers
          urls = [ "https://controlplane.tailscale.com/derpmap/default" ];
          auto_update_enabled = true;
          update_frequency = "24h";

          # Optional: Run your own DERP server
          # server = {
          #   enabled = true;
          #   region_id = 999;
          #   stun_listen_addr = "0.0.0.0:3478";
          # };
        };

        # Database configuration (SQLite is recommended)
        database = {
          type = "sqlite";
          sqlite = {
            path = "/var/lib/headscale/db.sqlite";
            write_ahead_log = true;
          };

          # PostgreSQL example (not recommended for new deployments)
          # type = "postgres";
          # postgres = {
          #   host = "localhost";
          #   port = 5432;
          #   name = "headscale";
          #   user = "headscale";
          #   password_file = "/run/secrets/headscale-db-password";
          # };
        };

        # Logging configuration
        log = {
          level = "info";
          format = "text";
        };

        # Optional: OIDC authentication
        # oidc = {
        #   issuer = "https://accounts.google.com";
        #   client_id = "your-client-id";
        #   client_secret_path = "/run/secrets/oidc-client-secret";
        #   scope = [ "openid" "profile" "email" ];
        #   allowed_domains = [ "example.com" ];
        # };

        # Optional: Let's Encrypt TLS certificates
        tls_letsencrypt_hostname = "hs.hawkstech.org";
        tls_letsencrypt_challenge_type = "HTTP-01";

        # Optional: Provide your own TLS certificates
        # tls_cert_path = "/path/to/cert.pem";
        # tls_key_path = "/path/to/key.pem";

        # ACL policy configuration
        policy = {
          mode = "file";
          path = "${aclFile}";
        };

        # You can add ANY headscale configuration option here thanks to freeform settings
        # For example, experimental features or settings not explicitly defined above:
        # experimental_feature = true;
        # custom_setting = "value";

        logtail.enabled = false;
      };
    };

    # Firewall configuration
    networking.firewall.allowPing = true;
    networking.firewall = {
      allowedTCPPorts = [3009];
      # If running a DERP server:
      # allowedUDPPorts = [ 3478 ];
    };

    # Create a systemd service to ensure the admin user exists
    systemd.services.headscale-ensure-admin = lib.mkIf config.services.headscale.enable {
      description = "Ensure Headscale admin user exists";
      after = ["headscale.service"];
      requires = ["headscale.service"];
      wantedBy = ["multi-user.target"];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "headscale";
        Group = "headscale";
      };

      script = ''
        # Check if user exists and create if needed
        if ! ${pkgs.headscale}/bin/headscale users list | grep -q "${adminUser}"; then
          echo "Creating headscale admin user: ${adminUser}"
          ${pkgs.headscale}/bin/headscale users create "${adminUser}"
        else
          echo "Headscale admin user ${adminUser} already exists"
        fi
      '';
    };
  };
}
