# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."gluetun" = {
    image = "qmcgaw/gluetun";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "SERVER_REGIONS" = "\"Norway,DE Berlin,DE Frankfurt,DE Germany Streaming Optimized\"";
      "TZ" = "America/New_York";
      "UPDATER_PERIOD" = "24h";
      "VPN_PORT_FORWARDING" = "on";
      "VPN_PORT_FORWARDING_STATUS_FILE" = "/gluetun/forwarded_port";
      "VPN_SERVICE_PROVIDER" = "private internet access";
    };
    environmentFiles = [
      "/run/agenix/gluetun-env"
    ];
    volumes = [
      "/data/config/gluetun:/gluetun:rw"
    ];
    ports = [
      "8888:8888/tcp"
      "8388:8388/tcp"
      "8388:8388/udp"
      "8081:8081/tcp"
      "6881:6881/tcp"
      "6881:6881/udp"
      "8090:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--health-cmd=ping -c 1 www.google.com || exit 1"
      "--health-interval=20s"
      "--health-retries=5"
      "--health-timeout=10s"
      "--network-alias=gluetun"
      "--network=bridge"
    ];
  };
  systemd.services."podman-gluetun" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-myarrstack-root.target"
    ];
    wantedBy = [
      "podman-compose-myarrstack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."qbittorrent" = {
    image = "lscr.io/linuxserver/qbittorrent:latest";
    environment = {
      "DOCKER_MODS" = "ghcr.io/techclusterhq/qbt-portchecker:main";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/New_York";
      "WEBUI_PORT" = "8081";
    };
    environmentFiles = [
      "/run/agenix/gluetun-env"
    ];
    volumes = [
      "/data/config/qbittorrent:/config:rw"
      "/data/media/downloads:/media/downloads:rw"
    ];
    labels = {
      "deunhealth.restart.on.unhealthy" = "true";
    };
    dependsOn = [
      "gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=ping -c 1 www.google.com || exit 1"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-start-period=20s"
      "--health-timeout=10s"
      "--network=container:gluetun"
    ];
  };
  systemd.services."podman-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-myarrstack-root.target"
    ];
    upheldBy = [
      "podman-gluetun.service"
    ];
    wantedBy = [
      "podman-compose-myarrstack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sabnzbd" = {
    image = "lscr.io/linuxserver/sabnzbd:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/New_York";
    };
    environmentFiles = [
      "/run/agenix/gluetun-env"
    ];
    volumes = [
      "/data/config/sabnzbd:/config:rw"
      "/data/media/downloads:/media/downloads:rw"
      "/data/media/downloads/incomplete:/media/downloads/incomplete:rw"
    ];
    dependsOn = [
      "gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:gluetun"
    ];
  };
  systemd.services."podman-sabnzbd" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-myarrstack-root.target"
    ];
    upheldBy = [
      "podman-gluetun.service"
    ];
    wantedBy = [
      "podman-compose-myarrstack-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-myarrstack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
